"""empty message

Revision ID: 15c332fb9dfe
Revises: eee68915cb3c
Create Date: 2018-02-19 20:42:48.982463

"""
from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, String
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15c332fb9dfe'
down_revision = None
branch_labels = None
depends_on = None

# job_status_table = table('job_status',
#                              column('job_status_id', Integer),
#                              column('job_status_name', String)
#                              )


def insert_data():
    job_status_table = sa.sql.table('job_status', sa.sql.column('job_status_id'), sa.sql.column('job_status_name'))
    op.bulk_insert(job_status_table,
                       [
                           {'job_status_id': 1, 'job_status_name': 'Completed'},
                           {'job_status_id': 2, 'job_status_name': 'Failed'},
                       ],
                       multiinsert=False
                       )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'job_status',
        sa.Column('job_status_id', sa.Integer(), nullable=False),
        sa.Column('job_status_name', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('job_status_id')
    )
    insert_data()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_status')
    # ### end Alembic commands ###
